#ifndef MESSAGETYPE_H_
#define MESSAGETYPE_H_

#define MSGTYPE_CHANGENEXT 1
#define MSGTYPE_PINGREQUEST 2
#define MSGTYPE_PINGREPLY 3
#define MSGTYPE_HEARTBEAT 4
#define MSGTYPE_PROCESSDEATH 5
#define MSGTYPE_ELECTION 6
#define MSGTYPE_VICTORY 7

#endif /* MESSAGETYPE_H_ */
